# Form implementation generated from reading ui file 'ApGuideActivity.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1300, 751)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1280, 730))
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1280, 730))
        self.label_3.setStyleSheet("border-image: url(Gui/images/background.png)\n""")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(1200, 0, 80, 730))
        self.label_4.setStyleSheet("background-color:rgba(0,0,0,80);")
        self.label_4.setObjectName("label_4")
        self.icon_home_2 = QtWidgets.QScrollArea(parent=self.widget)
        self.icon_home_2.setGeometry(QtCore.QRect(1220, 60, 40, 40))
        self.icon_home_2.setWidgetResizable(True)
        self.icon_home_2.setObjectName("icon_home_2")
        self.scrollAreaWidgetContents_11 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_11.setGeometry(QtCore.QRect(0, 0, 38, 38))
        self.scrollAreaWidgetContents_11.setObjectName("scrollAreaWidgetContents_11")
        self.pushButton_home = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_11)
        self.pushButton_home.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.pushButton_home.setObjectName("pushButton_home")
        self.icon_home_2.setWidget(self.scrollAreaWidgetContents_11)
        self.icon_calender_schedule_2 = QtWidgets.QScrollArea(parent=self.widget)
        self.icon_calender_schedule_2.setGeometry(QtCore.QRect(1220, 160, 40, 40))
        self.icon_calender_schedule_2.setWidgetResizable(True)
        self.icon_calender_schedule_2.setObjectName("icon_calender_schedule_2")
        self.scrollAreaWidgetContents_12 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_12.setGeometry(QtCore.QRect(0, 0, 38, 38))
        self.scrollAreaWidgetContents_12.setObjectName("scrollAreaWidgetContents_12")
        self.icon_calender_schedule_2.setWidget(self.scrollAreaWidgetContents_12)
        self.icon_apguide_2 = QtWidgets.QScrollArea(parent=self.widget)
        self.icon_apguide_2.setGeometry(QtCore.QRect(1220, 260, 40, 40))
        self.icon_apguide_2.setWidgetResizable(True)
        self.icon_apguide_2.setObjectName("icon_apguide_2")
        self.scrollAreaWidgetContents_13 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_13.setGeometry(QtCore.QRect(0, 0, 38, 38))
        self.scrollAreaWidgetContents_13.setObjectName("scrollAreaWidgetContents_13")
        self.pushButton_AP = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_13)
        self.pushButton_AP.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.pushButton_AP.setObjectName("pushButton_AP")
        self.icon_apguide_2.setWidget(self.scrollAreaWidgetContents_13)
        self.icon_calculater_2 = QtWidgets.QScrollArea(parent=self.widget)
        self.icon_calculater_2.setGeometry(QtCore.QRect(1220, 360, 40, 40))
        self.icon_calculater_2.setWidgetResizable(True)
        self.icon_calculater_2.setObjectName("icon_calculater_2")
        self.scrollAreaWidgetContents_14 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_14.setGeometry(QtCore.QRect(0, 0, 38, 38))
        self.scrollAreaWidgetContents_14.setObjectName("scrollAreaWidgetContents_14")
        self.icon_calculater_2.setWidget(self.scrollAreaWidgetContents_14)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1200, 730))
        self.label_5.setStyleSheet("background-color:rgba(0,0,0,180);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.tableView = QtWidgets.QTableView(parent=self.widget)
        self.tableView.setGeometry(QtCore.QRect(305, 15, 290, 700))
        self.tableView.setObjectName("tableView")
        self.tableView_2 = QtWidgets.QTableView(parent=self.widget)
        self.tableView_2.setGeometry(QtCore.QRect(600, 15, 290, 600))
        self.tableView_2.setObjectName("tableView_2")
        self.tableView_3 = QtWidgets.QTableView(parent=self.widget)
        self.tableView_3.setGeometry(QtCore.QRect(895, 15, 290, 600))
        self.tableView_3.setObjectName("tableView_3")
        self.tableView_4 = QtWidgets.QTableView(parent=self.widget)
        self.tableView_4.setGeometry(QtCore.QRect(15, 15, 250, 700))
        self.tableView_4.setObjectName("tableView_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_home.setText(_translate("Dialog", "PushButton"))
        self.pushButton_AP.setText(_translate("Dialog", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
